##
##  Docker compose file: NGINX, PHP, MYSQL, PHP-MYADMIN
##
##  to Start:
##  docker-compose up -d
##
##  to Stop:
##  docker-compose down
 
#version of Docker Compose file format
version: '2'

services:
    # THE WEB SERVER CONTAINER
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    
    #THE PHP CONTAINER
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network

  
    #THE MYSQL SERVER
    mysql:  #name of container
        image: mariadb:latest
        expose:
            - 3306
        volumes:
            - database_data:/vat/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: APProjects
            MYSQL_DATABASE: CarSharing
            MYSQL_USER: carUser
            MYSQL_PASSWORD: carPassword
    
    #PHP-MYADMIN
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8888:80
            
networks:
    code-network:
        driver: bridge
        
volumes:
    database_data:
        driver: local
