site: 
  build: .
  ports :
   - "8080:80"
  volumes:
   - ./www:/var/www/html/
  links:
   - database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8888:80"
   environment:
    - MYSQL_USERNAME=admin
    - MYSQL_PASSWORD=root
   links:
    - database:mysql
database:
  image: mysql:5.7
  ports:
   - "3306:3306"  
  environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=test
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=root